### ISSUE TITLE
BHop

### ISSUE THREAD

**Issue by HackerHansen** [Krunker-Java-plus-X/Krunker-JV-Hack#2]
Sounds like a dumb question but when is BHop coming out? I just need something that constantly jumps (even if the window is not currently focused) bc mine broke

**Comment by Krunker-Java-plus-X** [comment]
ok I will work hard at Bhop.
please wait for 3~5 days.

**Comment by Krunker-Java-plus-X** [comment]
I just post Bhop and ESP mods & hack pls see

**Comment by HackerHansen** [comment]
Thanks!
